# Generated by Django 4.1.7 on 2023-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
