# Generated by Django 4.1.7 on 2023-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='+91 ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='+91 ', max_length=10, null=True),
        ),
    ]
