# Generated by Django 4.0.3 on 2023-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_mobile_number_stockhistory_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='+91 ', null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='+91 ', null=True),
        ),
    ]
