# Generated by Django 4.1.7 on 2023-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
