# Generated by Django 4.1.7 on 2023-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='+91 ', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
