# Generated by Django 4.1.7 on 2023-04-17 06:17

import django.core.validators
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='receive_quantity',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='receive_quantity',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[inventory.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
