# Generated by Django 3.2.18 on 2023-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
