# Generated by Django 3.2.18 on 2023-05-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20230504_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
