# Generated by Django 3.2.18 on 2023-05-04 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
