# Generated by Django 3.2.18 on 2023-05-04 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20230504_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='issue_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True),
        ),
    ]
