# Generated by Django 3.2.18 on 2023-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20230504_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='issue_quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
