# Generated by Django 3.2.18 on 2023-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20230504_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='issue_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
