# Generated by Django 3.2.18 on 2023-05-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventory_issue_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='mobile_number',
        ),
    ]
